[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/shdb/nvim"
    refreshPeriod = "168h"
[".zsh.d"]
    type = "git-repo"
    url = "https://github.com/shdb/zsh-configs"
    refreshPeriod = "168h"
[".config/awesome"]
    type = "git-repo"
    url = "https://github.com/shdb/awesome-configs"
    refreshPeriod = "168h"
